name: feature-nodejs-pipeline

on:
  workflow_call:
    # Inputs are public configurations passed from the caller
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string  
      environment:
        required: true
        type: string    

jobs:
  feature-nodejs-pipeline:
    runs-on: self-hosted
    steps:
    - name: checkout code
      uses: actions/checkout@v6
    - name: list files
      run: ls -lrth
    - name: print inputs
      run: |
        echo ${{ inputs.project }}
        echo ${{ inputs.component }}
        echo ${{ inputs.environment }} 
    - name: Install NPM
      run: npm install
    - name: Test NPM
      run: npm test